### ISSUE TITLE
WisecondorX impact

### ISSUE THREAD

**Issue by Missthepast** [CenterForMedicalGeneticsGhent/PREFACE#12]
Hello, I would like to ask if there will be any impact on training when using **WisecondorX** for copy number normalization, and performing **seqtk trimfq -e 15** operation on the original reads to remove low-quality bases.

**Comment by matthdsm** [comment]
I'm not sure, haven't tested this. That being said, as long as all your samples are processed the same way, I don't see much issues.

Cheers
M
