### ISSUE TITLE
Calculation principle

### ISSUE THREAD

**Issue by Missthepast** [CenterForMedicalGeneticsGhent/PREFACE#13]
Sorry to bother you again. Can i set up calculations based on the X chromosome or autosomes? I understand that PREFACE defaults to calculations based on the Y chromosome.

**Comment by matthdsm** [comment]
If you know the exact fetal fraction you can use the `--femprop` option, but this is not advised.
https://github.com/CenterForMedicalGeneticsGhent/PREFACE?tab=readme-ov-file#model-training
