### ISSUE TITLE
Missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/PREFACE#2]
I just begin with bioinformatics. I have 90 samples treated with WisecondorX and the _bin.bed files have been used for training model. However I encountered this problem:

> Error in if (length(o)%%N != 0L) warning("number of items to replace is not a multiple of replacement length") : 
>   missing value where TRUE/FALSE needed
> Calls: train -> [<- -> [<-.data.frame
> Execution halted

Does anyone know what is my problem? I have tried multiple solutions but cannot solve this
This is the sample file I use for this run https://drive.google.com/file/d/1w8CwVV8-YlWQQBFsGjh_eufacxuPgf9P/view?usp=sharing

**Comment by leraman** [comment]
Hi @KhanhLPBao 

Thanks for the files, helps a lot.

I've made changes to solve this issue, you can find them here:
https://github.com/CenterForMedicalGeneticsGhent/PREFACE/releases/tag/v0.1.2
