### ISSUE TITLE
Script cannot read config file even though it is stripped out of the example file

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/PREFACE#4]
I tried to make the model for prediction FF from 852 samples. However everytime I run the script returned this error

> Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
>   scan() expected 'a real', got 'n/a'
> Calls: train -> read.csv -> read.table -> scan
> Execution halted
> 
Even though I have download the example config file and rename all of my samples like on the config with adjust the path. It still give me that error. I'm using R 3.6.3 to run PREFACE

**Comment by leraman** [comment]
What do you mean with 'stripped out of the example file'? The error states you have missing values formatted as 'n/a'?

**Comment by KhanhLPBao** [comment]
I mean I copy the config file and then just modified the ff and gender. I have recheck the file and found a typo. Thank you very much

**Comment by smruti241** [comment]
Hii @KhanhLPBao  I am using PREFACE after WISECONDOR for fetal fraction detection. I got the point how to create bed file but i ma not getting where to get config file? I have raised this issue too but didnt get reply. I hope you have worked on all these tools, so need your help. Please help me regarding this. I am trying for the last 2 months but getting partial knowledge only.

**Comment by smruti241** [comment]
> I mean I copy the config file and then just modified the ff and gender. I have recheck the file and found a typo. Thank you very much

Please help me
