### ISSUE TITLE
Preparation of config file

### ISSUE THREAD

**Issue by smruti241** [CenterForMedicalGeneticsGhent/PREFACE#7]
Please guide me how to prepare config.txt file. I dont understand what IDs I need to provide and what bed files I have to mention. Since I dont know the gender of any of the samples then how do I know it. How can I calculate the fetal fraction. Please guide me.

**Comment by smruti241** [comment]
Please guide me how to create config.txt file. I dont know about fetal sex and it is unknown sample so how can i make config file?

**Comment by smruti241** [comment]
Please someone help me regarding this. I am not finding how to create config.txt file. In README, it is not mentioned too. I dont know why authors dont give proper detailed things on their tools or software. I dont know how to make config file in case of unknown sample or gender.

**Comment by KhanhLPBao** [comment]
@smruti241 The easiest way to create the config file is via Microsoft Excel. Save the name into first column, the path to the file on the second column, gender (M or F) on third column and fetal fraction in fourth column. then choose File -> Save As -> Choose file type is Text (tab delimited) and then save the file

**Comment by smruti241** [comment]
@KhanhLPBao I know that but if I dont know about the gender and fetal fraction, then how can I create it? thats my question. If i will create the gender and fetal fraction, then what PREFACE will do? Please tell me how to calculate fetal fraction and determine gender? is there any other tool you used?

**Comment by leraman** [comment]
Hi @smruti241,

You will have to do some custom parsing on the bam files to obtain a good FFY measure for your setup. We do not provide code for this. The same goes for the config file, you'll have to parse it yourself.

**Comment by smruti241** [comment]
@leraman can you please tell me the logic how to parse bam files to obtain FFY measure so that I can write a code.

**Comment by KhanhLPBao** [comment]
@smruti241 you need multiple reference file that you know clearly about the gender and fetal fraction (by lab work or by another prediction methods) so PREFACE can based on those files to predict.

**Comment by smruti241** [comment]
Thank you @KhanhLPBao for this information.
